apiVersion: v1
kind: Service
metadata:
  name: go-sample-service
  labels:
    app: go-sample-service
spec:
  selector:
    app: go-sample-service
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: my-port
